# Generated by Django 3.0.8 on 2020-08-22 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='catefory',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated',
        ),
    ]
